// This is the schema of the JSON output generated by
// https://gist.github.com/ikatson/cee88cc50c52f10abdd4ea02d29cc644

export interface Schema {
    name: string,
    type: "provider",
    version: string,
    provider: SchemaInfo,
    resources: SchemaInfos,
    "data-sources": SchemaInfos,
}

export type SchemaInfo = {[propName: string]: TypeDescription}
export type SchemaInfos = {
    [propName: string]: SchemaInfo
}

export enum Type {
    TypeString = "TypeString",
    TypeSet = "TypeSet",
    TypeList = "TypeList",
    TypeInt = "TypeInt",
    TypeFloat = "TypeFloat",
    TypeMap = "TypeMap",
    TypeBool = "TypeBool",
    SchemaInfo = "SchemaInfo",
    SchemaElements = "SchemaElements",
}

export interface TypeDescription {
    Type: Type,
    Required: boolean,
    Optional: boolean,
    Description: string,
    Removed: string,
    Computed: boolean,
    Default: any
    Elem: Elem
}

export interface Elem {
    Type: Type,
    ElementsType: Type,
    Info: SchemaInfo,
}